CREATE TABLE IF NOT EXISTS dim_ssga_fund (
   ssga_fund_base_id    bigint                         not null,
   ssga_fund_hist_id    bigint                         not null,
   asof_calendar_day    date,
   ssga_batch_base_id   bigint                         not null,
   account_as_fund_flag character varying(10)          not null,
   fund_id              bigint                         not null,
   portia_alias         character varying(13),
   prks_alias           character varying(13),
   aladdin_alias        character varying(13),
   champs_alias         character varying(13),
   accounting_system    character varying(255),
   cost_center          character varying(255),
   fund_domicile        character varying(255),
   legal_name           character varying(255),
   legal_type           character varying(100),
   management_location  character varying(255),
   market_effect_eligibility character varying(100),
   opening_frequency    character varying(100),
   portfolio_type       character varying(100),
   portfolio_type_sub_class character varying(100),
   region               character varying(255),
   selection_strategy   character varying(255),
   strategy             character varying(255),
   structure            character varying(100),
   subadvisor           character varying(255),
   subadvisory          character varying(100),
   commencement_op_calendar_day date,
   start_calendar_day   date,
   stop_calendar_day    date,
   trading_start_calendar_day date,
   trading_stop_calendar_day date,
   termination_calendar_day date,
   active_sel_approach  character varying(255),
   alt_sub_asset_type   character varying(100),
   asset_class          character varying(100),
   asset_source         character varying(255),
   company_stock        character varying(255),
   advisory_bool        boolean,
   currency_sector      character varying(100),
   duration             character varying(100),
   hedge_ast_mgmt_source character varying(255),
   hedge_ast_mgmt_source_code character varying(20),
   inv_approach         character varying(255),
   inv_country_code     character varying(50),
   inv_region           character varying(255),
   inv_style            character varying(100),
   inv_subregion        character varying(255),
   market_cap           character varying(100),
   nav_subattr_type     character varying(100),
   nav_type             character varying(100),
   product_strategy     character varying(255),
   sector_fi            character varying(100),
   style                character varying(100),
   underlying           character varying(100),
   underlying_code      character varying(20),
   traded_on_exchange_flag character varying(50),
   isg_managed_bool     boolean,
   fund_group           character varying(255),
   fund_group_type      character varying(100),
   sub_advised_flag     character varying(5),
   corporate_action_system_flag character varying(5),
   do_not_invest_accrued_income_flag character varying(5),
   do_not_invest_disinvest_fx_for_flag character varying(5),
   do_not_invest_paid_income_flag character varying(5),
   fx_fund_trading_strategy_flag character varying(5),
   fx_trading_type_eligible_flag character varying(5),
   internal_crossing_eligible_flag character varying(5),
   ipo_eligible_flag    character varying(5),
   latent_zero_sentinel_eligible_flag character varying(5),
   proxy_voting_discretion_flag character varying(5),
   securities_lending_status_flag character varying(50),
   soft_commission_eligible_flag character varying(5),
   ssga_fm_cta_client_sma_only_flag character varying(5),
   trade_order_routing_flag character varying(5),
   value_reported_to_aum_flag character varying(5),
   nsrd_fund_alias      character varying(13),
   corporate_bool       character varying(5),
   long_short_bool      character varying(5),
   inv_grade_bool       character varying(5),
   synthetic_exposure_over_90_bool character varying(5),
   portfolio_manager    character varying(255),
   registration_flag    character varying(255),
   traded_on_exchange   character varying(50),
   legal_type_subclassification character varying(50),
   select_concentrated  character varying(20),
   temc                 character varying(20),
   ldi                  character varying(20),
   exposure_management  character varying(20),
   currency_hedged      character varying(20),
   benchmark_code       character varying(100),
   benchmark_name       character varying(100),
   lqr_fund_cluster     character varying(100),
   fund_proxy_account_id bigint,
   custody_alias        character varying(13),
   isin_alias           character varying(13),
   ticker_alias         character varying(13),
   effective_timestamp  timestamp                      not null  DEFAULT CAST(SYSDATE AT TIME ZONE 'UTC' AS TIMESTAMP),
   aggressiveness       character varying(100),
   active_sel_approach_code character varying(20),
   alt_sub_asset_type_code character varying(20),
   approach             character varying(255),
   approach_code        character varying(20),
   asset_class_code     character varying(20),
   asset_source_code    character varying(20),
   company_stock_code   character varying(20),
   currency_hedged_bool boolean,
   currency_sector_code character varying(20),
   duration_code        character varying(20),
   exposure_management_bool boolean,
   inv_approach_code    character varying(20),
   inv_country          character varying(255),
   inv_region_code      character varying(20),
   inv_style_code       character varying(20),
   inv_subregion_code   character varying(20),
   market_cap_code      character varying(20),
   nav_subattr_type_code character varying(20),
   nav_type_code        character varying(20),
   product_strategy_code character varying(20),
   sector_fi_code       character varying(20),
   style_code           character varying(20),
   syn_exp_bool         boolean,
   temc_bool            boolean,
   advisory             character varying(20),
   isg_managed_flag     character varying(80),
   contracting_entity   character varying(255),
   accounting_currency  character varying(4),
   lei                  character varying(20),
   proxy_account_prks_alias character varying(13),
   registration_type    character varying(255),
   nsrd_fund_alias_start_day date,
   nsrd_fund_alias_stop_day date,
   portia_alias_start_day date,
   portia_alias_stop_day date,
   prks_alias_start_day date,
   prks_alias_stop_day  date,
   custody_alias_start_day date,
   custody_alias_stop_day date,
   isin_start_day       date,
   isin_stop_day        date,
   ticker_start_day     date,
   ticker_stop_day      date,
   aladdin_alias_start_day date,
   aladdin_alias_stop_day date,
   champs_alias_start_day date,
   champs_alias_stop_day date,
   caca_alias           character varying(13),
   caca_alias_start_day date,
   caca_alias_stop_day  date,
   future_clearing_broker character varying(255),
   future_clearing_broker_parent character varying(255),
   futures_clearing_account character varying(255),
   ssga_data_source_base_id bigint                         not null,
   synthetic_fund_alias character varying(100),
   synthetic_fund_id    bigint,
   fund_range           character varying(255),
   custodian            character varying(1000),
   prime_broker         character varying(255),
   ifast_alias          character varying(13),
   ifast_alias_start_day date,
   ifast_alias_stop_day date
)
DISTSTYLE KEY
DISTKEY (SSGA_fund_base_id)
SORTKEY (asof_calendar_day);

CREATE TABLE IF NOT EXISTS dim_ssga_security (
   ssga_security_hist_id bigint                         not null,
   ssga_security_base_id bigint                         not null,
   ssga_batch_base_id   bigint                         not null,
   ssga_security_id     integer                        not null,
   accrued_factor       numeric(18,8),
   asset_type           character varying(28),
   amount_issued        numeric(30,12),
   callable_flag        character varying(1),
   convertible_flag     character varying(1),
   collateral_type      character varying(40),
   country_of_issuer_iso_code character varying(60),
   country_of_risk_iso_code character varying(60),
   coupon_rate          numeric(20,4),
   coupon_type          character varying(24),
   cusip                character varying(40),
   dbrs_rating          character varying(12),
   expected_maturity_calendar_day timestamp,
   fitch_lt_mmkt_rating character varying(20),
   fitch_lt_rating      character varying(20),
   fitch_lt_rating_calendar_day timestamp,
   fitch_lt_rating_source character varying(20),
   fitch_lt_rating_type character varying(600),
   fitch_prog_mmkt_rating character varying(20),
   fitch_st_mmkt_rating character varying(20),
   fitch_st_rating      character varying(20),
   fitch_st_rating_calendar_day timestamp,
   fitch_st_rating_source character varying(20),
   fitch_st_rating_type character varying(600),
   floater_flag         character varying(1),
   fund_typ             character varying(40),
   gics_industry_group_code character varying(40),
   gics_industry_group_name character varying(60),
   gics_sector_code     character varying(40),
   gics_sector_name     character varying(60),
   gics_industry_code   character varying(40),
   gics_industry_name   character varying(60),
   gics_sub_industry_code character varying(40),
   gics_sub_industry_name character varying(60),
   immediate_parent_id  character varying(255),
   immediate_parent_name character varying(100),
   industry_group       character varying(24),
   industry_sector      character varying(24),
   industry_subgroup    character varying(30),
   internal_security_id_mdf bigint,
   internal_security_id_gcdf numeric(38,0),
   internal_security_id_idr numeric(38,0),
   internal_security_id_fa character varying(20),
   isin                 character varying(40),
   issue_calendar_day   timestamp,
   issuer_id            bigint,
   issuer_industry      character varying(16),
   issuer_name          character varying(128),
   last_refix_calendar_day timestamp,
   market_sector_description character varying(6),
   maturity_calendar_day timestamp,
   moodys_lt_mmkt_rating character varying(20),
   moodys_lt_rating     character varying(20),
   moodys_lt_rating_calendar_day timestamp,
   moodys_lt_rating_source character varying(20),
   moodys_lt_rating_type character varying(600),
   moodys_prog_mmkt_rating character varying(20),
   moodys_st_mmkt_rating character varying(20),
   moodys_st_rating     character varying(20),
   moodys_st_rating_calendar_day timestamp,
   moodys_st_rating_source character varying(20),
   moodys_st_rating_type character varying(600),
   mortgage_credit_provider character varying(8),
   mortgage_series      character varying(8),
   mortgage_servicer    character varying(4000),
   next_call_calendar_day timestamp,
   next_payment_calendar_day timestamp,
   next_put_calendar_day timestamp,
   next_reset_calendar_day timestamp,
   outstanding_amount   numeric(30,12),
   par_amount           numeric(38,14),
   putable_flag         character varying(1),
   pv_asset_class       character varying(255),
   pv_sector            character varying(80),
   pv_sector_detail     character varying(80),
   sp_lt_watchlist_direction character varying(20),
   sp_lt_watchlist_timestamp timestamp,
   sp_st_watchlist_direction character varying(20),
   sp_st_watchlist_timestamp timestamp,
   fitch_lt_watchlist_direction character varying(20),
   fitch_lt_watchlist_timestamp timestamp,
   fitch_st_watchlist_direction character varying(20),
   fitch_st_watchlist_timestamp timestamp,
   moodys_lt_watchlist_direction character varying(20),
   moodys_lt_watchlist_timestamp timestamp,
   moodys_st_watchlist_direction character varying(20),
   moodys_st_watchlist_timestamp timestamp,
   portia_key           character varying(40),
   refix_frequency      character varying(30),
   remaining_maturity   numeric(30,12),
   repo_collateral_name character varying(60),
   repo_collateral_type character varying(20),
   repo_ext_calendar_day timestamp,
   repo_open_flag       character varying(20),
   reset_index          character varying(15),
   sec_days             character varying(20),
   security_description character varying(600),
   security_type        character varying(32),
   sector               character varying(30),
   subsector            character varying(30),
   sp_lt_mmkt_rating    character varying(20),
   sp_lt_rating         character varying(20),
   sp_lt_rating_calendar_day timestamp,
   sp_lt_rating_source  character varying(20),
   sp_lt_rating_type    character varying(600),
   sp_prog_mmkt_rating  character varying(20),
   sp_st_mmkt_rating    character varying(20),
   sp_st_rating         character varying(20),
   sp_st_rating_calendar_day timestamp,
   sp_st_rating_source  character varying(20),
   sp_st_rating_type    character varying(600),
   sponsor              character varying(80),
   ultimate_parent_name character varying(100),
   ultimate_parent      character varying(255),
   yield_to_maturity    numeric(18,7),
   underlying_type      character varying(20),
   underlying_ssga_security_id character varying(40),
   report_timestamp     timestamp,
   swap_type            character varying(15),
   pay_leg_currency     character varying(10),
   rec_leg_currency     character varying(10),
   pay_leg_float_rate_ref character varying(45),
   rec_leg_float_rate_ref character varying(45),
   rec_leg_type         character varying(20),
   rec_leg_fixed_rate   numeric(38,16),
   pay_leg_type         character varying(20),
   pay_leg_fixed_rate   numeric(38,16),
   product_type         character varying(20),
   otc_original_counterparty character varying(45),
   otc_start_timestamp  timestamp,
   otc_end_timestamp    timestamp,
   pay_leg_spread       numeric(30,12),
   pay_leg_rolling_period_count integer,
   pay_leg_rolling_period_unit character varying(10),
   pay_leg_day_count    character varying(15),
   pay_leg_reset_period_count integer,
   pay_leg_reset_period_unit character varying(10),
   pay_leg_reset_type   character varying(15),
   rec_leg_spread       numeric(30,12),
   rec_leg_rolling_period_count integer,
   rec_leg_rolling_period_unit character varying(10),
   rec_leg_day_count    character varying(15),
   rec_leg_reset_period_count integer,
   rec_leg_reset_period_unit character varying(10),
   rec_leg_reset_type   character varying(15),
   used_price_end       numeric(38,16),
   base_index           character varying(45),
   base_index_type      character varying(30),
   base_index_value     numeric(30,12),
   traded_fixed_rate    numeric(30,12),
   otc_traded_backend_notional numeric(30,12),
   otc_traded_frontend_notional numeric(30,12),
   otc_contract_size    numeric(38,16),
   repo_notice_period_count integer,
   repo_notice_period_unit character varying(10),
   strike_price         numeric(30,12),
   sec_id               character varying(30),
   private_placement_flag character varying(1),
   guarantor_id         character varying(255),
   coupon_currency_iso_code character varying(4),
   coupon_payment_frequency bigint,
   expiration_timestamp timestamp,
   optn_id              character varying(40),
   shares_outstanding   numeric(38,6),
   bb_security_id       character varying(30),
   not_in_stage_bool    boolean,
   flag_144a            character varying(1),
   is_reg_s             character varying(1),
   inflation_linked_indicator character varying(1),
   type_of_bond         character varying(100),
   future_category      character varying(100),
   cadis_system_uptimestampd timestamp,
   effective_timestamp  timestamp                      not null  DEFAULT CAST(SYSDATE AT TIME ZONE 'UTC' AS TIMESTAMP),
   final_maturity_date  date,
   prks                 character varying(40),
   mch_id               character varying(40),
   bb_id                character varying(40),
   future_first_trade_date date,
   next_call_price      numeric(22,6),
   next_put_price       numeric(22,6),
   floater_spread       numeric(12,3),
   future_contract_size numeric(18,2),
   future_first_delivery_date date,
   future_last_delivery_date date,
   gcdf_application_key character varying(30),
   clearing_exchange_code character varying(39),
   cins                 character varying(40),
   future_ric_root      character varying(40),
   alt_root_alias       character varying(40),
   executing_broker     character varying(45)
)
DISTSTYLE KEY
DISTKEY (SSGA_security_base_id);



CREATE TABLE IF NOT EXISTS dim_ssga_security_exchange (
   ssga_security_exchange_hist_id bigint                         not null,
   ssga_security_exchange_base_id bigint                         not null,
   ssga_batch_base_id   bigint                         not null,
   issue_id             bigint                         not null,
   ssga_security_id     integer,
   issue_currency_iso_code character varying(4),
   sedol                character varying(40),
   country_of_trading_iso_code character varying(50),
   primary_exchange_flag character(1),
   mic_code             character varying(50),
   rks_key              character varying(40),
   ric                  character varying(40),
   ticker               character varying(40),
   id_bb_unique         character varying(40),
   not_in_stage_bool    boolean,
   cadis_system_updated timestamp                      not null,
   id_bb_global         character varying(50),
   composite_id_bb_global character varying(50),
   exch_code            character varying(20),
   effective_timestamp  timestamp                      not null  DEFAULT CAST(SYSDATE AT TIME ZONE 'UTC' AS TIMESTAMP)
)
DISTSTYLE KEY
DISTKEY (SSGA_security_exchange_base_id);
