CREATE TABLE IF NOT EXISTS dim_ssga_security (
   ssga_security_hist_id bigint                         not null,
   ssga_security_base_id bigint                         not null,
   ssga_batch_base_id   bigint                         not null,
   ssga_security_id     integer                        not null,
   accrued_factor       numeric(18,8),
   asset_type           character varying(28),
   amount_issued        numeric(30,12),
   callable_flag        character varying(1),
   convertible_flag     character varying(1),
   collateral_type      character varying(40),
   country_of_issuer_iso_code character varying(60),
   country_of_risk_iso_code character varying(60),
   coupon_rate          numeric(20,4),
   coupon_type          character varying(24),
   cusip                character varying(40),
   dbrs_rating          character varying(12),
   expected_maturity_calendar_day timestamp,
   fitch_lt_mmkt_rating character varying(20),
   fitch_lt_rating      character varying(20),
   fitch_lt_rating_calendar_day timestamp,
   fitch_lt_rating_source character varying(20),
   fitch_lt_rating_type character varying(600),
   fitch_prog_mmkt_rating character varying(20),
   fitch_st_mmkt_rating character varying(20),
   fitch_st_rating      character varying(20),
   fitch_st_rating_calendar_day timestamp,
   fitch_st_rating_source character varying(20),
   fitch_st_rating_type character varying(600),
   floater_flag         character varying(1),
   fund_typ             character varying(40),
   gics_industry_group_code character varying(40),
   gics_industry_group_name character varying(60),
   gics_sector_code     character varying(40),
   gics_sector_name     character varying(60),
   gics_industry_code   character varying(40),
   gics_industry_name   character varying(60),
   gics_sub_industry_code character varying(40),
   gics_sub_industry_name character varying(60),
   immediate_parent_id  character varying(255),
   immediate_parent_name character varying(100),
   industry_group       character varying(24),
   industry_sector      character varying(24),
   industry_subgroup    character varying(30),
   internal_security_id_mdf bigint,
   internal_security_id_gcdf numeric(38,0),
   internal_security_id_idr numeric(38,0),
   internal_security_id_fa character varying(20),
   isin                 character varying(40),
   issue_calendar_day   timestamp,
   issuer_id            bigint,
   issuer_industry      character varying(16),
   issuer_name          character varying(128),
   last_refix_calendar_day timestamp,
   market_sector_description character varying(6),
   maturity_calendar_day timestamp,
   moodys_lt_mmkt_rating character varying(20),
   moodys_lt_rating     character varying(20),
   moodys_lt_rating_calendar_day timestamp,
   moodys_lt_rating_source character varying(20),
   moodys_lt_rating_type character varying(600),
   moodys_prog_mmkt_rating character varying(20),
   moodys_st_mmkt_rating character varying(20),
   moodys_st_rating     character varying(20),
   moodys_st_rating_calendar_day timestamp,
   moodys_st_rating_source character varying(20),
   moodys_st_rating_type character varying(600),
   mortgage_credit_provider character varying(8),
   mortgage_series      character varying(8),
   mortgage_servicer    character varying(4000),
   next_call_calendar_day timestamp,
   next_payment_calendar_day timestamp,
   next_put_calendar_day timestamp,
   next_reset_calendar_day timestamp,
   outstanding_amount   numeric(30,12),
   par_amount           numeric(38,14),
   putable_flag         character varying(1),
   pv_asset_class       character varying(255),
   pv_sector            character varying(80),
   pv_sector_detail     character varying(80),
   sp_lt_watchlist_direction character varying(20),
   sp_lt_watchlist_timestamp timestamp,
   sp_st_watchlist_direction character varying(20),
   sp_st_watchlist_timestamp timestamp,
   fitch_lt_watchlist_direction character varying(20),
   fitch_lt_watchlist_timestamp timestamp,
   fitch_st_watchlist_direction character varying(20),
   fitch_st_watchlist_timestamp timestamp,
   moodys_lt_watchlist_direction character varying(20),
   moodys_lt_watchlist_timestamp timestamp,
   moodys_st_watchlist_direction character varying(20),
   moodys_st_watchlist_timestamp timestamp,
   portia_key           character varying(40),
   refix_frequency      character varying(30),
   remaining_maturity   numeric(30,12),
   repo_collateral_name character varying(60),
   repo_collateral_type character varying(20),
   repo_ext_calendar_day timestamp,
   repo_open_flag       character varying(20),
   reset_index          character varying(15),
   sec_days             character varying(20),
   security_description character varying(600),
   security_type        character varying(32),
   sector               character varying(30),
   subsector            character varying(30),
   sp_lt_mmkt_rating    character varying(20),
   sp_lt_rating         character varying(20),
   sp_lt_rating_calendar_day timestamp,
   sp_lt_rating_source  character varying(20),
   sp_lt_rating_type    character varying(600),
   sp_prog_mmkt_rating  character varying(20),
   sp_st_mmkt_rating    character varying(20),
   sp_st_rating         character varying(20),
   sp_st_rating_calendar_day timestamp,
   sp_st_rating_source  character varying(20),
   sp_st_rating_type    character varying(600),
   sponsor              character varying(80),
   ultimate_parent_name character varying(100),
   ultimate_parent      character varying(255),
   yield_to_maturity    numeric(18,7),
   underlying_type      character varying(20),
   underlying_ssga_security_id character varying(40),
   report_timestamp     timestamp,
   swap_type            character varying(15),
   pay_leg_currency     character varying(10),
   rec_leg_currency     character varying(10),
   pay_leg_float_rate_ref character varying(45),
   rec_leg_float_rate_ref character varying(45),
   rec_leg_type         character varying(20),
   rec_leg_fixed_rate   numeric(38,16),
   pay_leg_type         character varying(20),
   pay_leg_fixed_rate   numeric(38,16),
   product_type         character varying(20),
   otc_original_counterparty character varying(45),
   otc_start_timestamp  timestamp,
   otc_end_timestamp    timestamp,
   pay_leg_spread       numeric(30,12),
   pay_leg_rolling_period_count integer,
   pay_leg_rolling_period_unit character varying(10),
   pay_leg_day_count    character varying(15),
   pay_leg_reset_period_count integer,
   pay_leg_reset_period_unit character varying(10),
   pay_leg_reset_type   character varying(15),
   rec_leg_spread       numeric(30,12),
   rec_leg_rolling_period_count integer,
   rec_leg_rolling_period_unit character varying(10),
   rec_leg_day_count    character varying(15),
   rec_leg_reset_period_count integer,
   rec_leg_reset_period_unit character varying(10),
   rec_leg_reset_type   character varying(15),
   used_price_end       numeric(38,16),
   base_index           character varying(45),
   base_index_type      character varying(30),
   base_index_value     numeric(30,12),
   traded_fixed_rate    numeric(30,12),
   otc_traded_backend_notional numeric(30,12),
   otc_traded_frontend_notional numeric(30,12),
   otc_contract_size    numeric(38,16),
   repo_notice_period_count integer,
   repo_notice_period_unit character varying(10),
   strike_price         numeric(30,12),
   sec_id               character varying(30),
   private_placement_flag character varying(1),
   guarantor_id         character varying(255),
   coupon_currency_iso_code character varying(4),
   coupon_payment_frequency bigint,
   expiration_timestamp timestamp,
   optn_id              character varying(40),
   shares_outstanding   numeric(38,6),
   bb_security_id       character varying(30),
   not_in_stage_bool    boolean,
   flag_144a            character varying(1),
   is_reg_s             character varying(1),
   inflation_linked_indicator character varying(1),
   type_of_bond         character varying(100),
   future_category      character varying(100),
   cadis_system_uptimestampd timestamp,
   effective_timestamp  timestamp                      not null  DEFAULT CAST(SYSDATE AT TIME ZONE 'UTC' AS TIMESTAMP),
   final_maturity_date  date,
   prks                 character varying(40),
   mch_id               character varying(40),
   bb_id                character varying(40),
   future_first_trade_date date,
   next_call_price      numeric(22,6),
   next_put_price       numeric(22,6),
   floater_spread       numeric(12,3),
   future_contract_size numeric(18,2),
   future_first_delivery_date date,
   future_last_delivery_date date,
   gcdf_application_key character varying(30),
   clearing_exchange_code character varying(39),
   cins                 character varying(40),
   future_ric_root      character varying(40),
   alt_root_alias       character varying(40),
   executing_broker     character varying(45)
)
DISTSTYLE KEY
DISTKEY (SSGA_security_base_id);
